### ISSUE TITLE
The paper mentioned that there is a cuda implementation for algorithm P, is it possible to open source that?

### ISSUE THREAD

**Issue by aaroey** [lorenzhs/sampling#1]

**Comment by lorenzhs** [comment]
~~[sampling/methodP.hpp](https://github.com/lorenzhs/sampling/blob/master/sampling/methodP.hpp) and [benchmark/run_methodP.cpp](https://github.com/lorenzhs/sampling/blob/master/benchmark/run_methodP.cpp) should be what you are looking for.~~

Edit: sorry, reading skills. Pinging @e-schrade who wrote the CUDA bits.

**Comment by lorenzhs** [comment]
Just added it, it's in [cuda_gen.cu](https://github.com/lorenzhs/sampling/blob/master/cuda_gen.cu).

**Comment by asgetz** [comment]
Thank you so much
